#!/bin/sh
set -e
[ "$1" = purge ] && rm -rf /etc/usb-over-ip
if [ -d /run/systemd/system ]; then
  systemctl daemon-reload
  udevadm control --reload-rules || true
  # ser2net goes back to its own /etc/ser2net.yaml
  [ "$1" = remove ] && systemctl try-restart ser2net.service || true
fi
